#!/usr/bin/env bash
# inventory_writable_paths.sh — AC-1 of FIX-BOT-RUNTIME-WORKTREE-ISOLATION-01.
#
# Generates an exhaustive inventory of every writable path the bot tree
# currently assumes. Output drives the symlink farm in deploy_bot_prod.sh
# so a "read-only" prod tree does not silently lose writes.
#
# AUDITOR Lane B input #1: this AC must complete and be reviewed before
# any refactor begins. Without it AC-3 / AC-5 cannot be reasoned about.
#
# Usage:
#   bash scripts/inventory_writable_paths.sh           # human-readable summary
#   bash scripts/inventory_writable_paths.sh --md      # markdown report

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BOT_TREE="${BOT_TREE:-/home/paulsportsza/bot}"
MODE="${1:-text}"

cd "$BOT_TREE"

emit() {
    if [ "$MODE" = "--md" ]; then
        printf '%s\n' "$1"
    else
        printf '%s\n' "$1"
    fi
}

emit_section() {
    if [ "$MODE" = "--md" ]; then
        printf '\n## %s\n\n```\n' "$1"
    else
        printf '\n=== %s ===\n' "$1"
    fi
}

end_section() {
    if [ "$MODE" = "--md" ]; then
        printf '```\n'
    fi
}

if [ "$MODE" = "--md" ]; then
    cat <<EOF
# Bot Tree — Writable Paths Inventory

Generated by \`scripts/inventory_writable_paths.sh\` for
FIX-BOT-RUNTIME-WORKTREE-ISOLATION-01 (AC-1).

Source tree: \`$BOT_TREE\`
Generated: $(date -Is)

This document enumerates every writable filesystem path the bot runtime
touches. Each section is grep evidence; the consolidated symlink farm at
the end is what \`deploy_bot_prod.sh\` provisions on top of the read-only
prod tree.

EOF
fi

emit_section "sqlite write helpers (production code)"
grep -rn 'connect_odds_db(' --include='*.py' . 2>/dev/null \
    | grep -v 'readonly' \
    | grep -v '/tests/' \
    | grep -v 'test_' || true
grep -rn 'get_connection(' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' || true
end_section

emit_section "file write APIs (production code)"
grep -rnE "open\(.*['\"](w|a|w\+|a\+|wb|ab)" --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' || true
grep -rn 'write_text\|write_bytes' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' || true
end_section

emit_section "Path(__file__).parent resolution sites (production code)"
grep -rn 'Path(__file__).parent' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' || true
grep -rn 'os.path.dirname(__file__)' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' || true
end_section

emit_section "known db files referenced by name (production code)"
for db in odds.db mzansiedge.db edge.db narrative_cache.db logo_cache.db \
          bot_data.db bet_log.db bot.db edges.db moq.db mzansi_bot.db \
          card_file_ids.db edge_scrapers.db narratives.db sports.db \
          mzansi_edge.db scrapers.db mzansi.db; do
    hits=$(grep -rln "$db" --include='*.py' . 2>/dev/null \
        | grep -v '/tests/' \
        | grep -v 'test_' || true)
    if [ -n "$hits" ]; then
        emit "## $db"
        printf '%s\n' "$hits"
    fi
done
end_section

emit_section "data/ reports/ logs/ bet_log/ directory references (production code)"
grep -rnE '(reports|logs|bet_log)/' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' \
    | head -60 || true
echo ''
echo '--- data/ specifically ---'
grep -rn '"data/' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' \
    | head -40 || true
end_section

emit_section "shutil / os.makedirs / mkdir (production code)"
grep -rnE 'shutil\.copy|shutil\.move|shutil\.rmtree|os\.makedirs|os\.mkdir|Path\(.*\)\.mkdir' --include='*.py' . 2>/dev/null \
    | grep -v '/tests/' \
    | grep -v 'test_' \
    | head -40 || true
end_section

emit_section "physical files / dirs in bot tree (top level)"
ls -la "$BOT_TREE"/*.db 2>/dev/null || echo '(no top-level .db files)'
echo ''
echo '--- bot_tree/data ---'
ls -la "$BOT_TREE/data/" 2>/dev/null | head -30 || true
echo ''
echo '--- bot_tree/reports ---'
ls -la "$BOT_TREE/reports/" 2>/dev/null | head -10 || true
echo ''
echo '--- bot_tree/logs ---'
ls -la "$BOT_TREE/logs/" 2>/dev/null | head -10 || true
echo ''
echo '--- bot_tree/bet_log ---'
ls -la "$BOT_TREE/bet_log/" 2>/dev/null | head -10 || echo '(absent)'
end_section

if [ "$MODE" = "--md" ]; then
    cat <<'EOF'

## Symlink-farm decision (writes redirected to bot-data-shared)

The following bot-tree subtrees become symlinks in the prod runtime
(`/home/paulsportsza/bot-prod/<sub>` → `/home/paulsportsza/bot-data-shared/<sub>`):

| Sub-path | Why writable |
|---|---|
| `data/` | All in-bot SQLite DBs (narrative_cache, logo_cache, edge, mzansiedge, etc.) |
| `reports/` | wave + QA report markdown / JSON |
| `logs/` | rotating log files |
| `bet_log/` | settlement bet log (created on demand by `bet_log_writer`) |
| `__pycache__/` (PYTHONPYCACHEPREFIX) | redirected to `bot-data-shared/pycache/` via systemd Environment so chmod -R u-w on the prod tree does not block bytecode caching |

`scrapers/odds.db` (855 MB) is **not** under bot/, it lives at
`/home/paulsportsza/scrapers/odds.db`. `Path(__file__).parent.parent /
"scrapers"` resolves identically from both `/home/paulsportsza/bot/` and
`/home/paulsportsza/bot-prod/`, so no symlink is needed for the scrapers
DB — the path resolution itself is location-stable.

Top-level DBs that exist as bare files in `/home/paulsportsza/bot/` (not
under `data/`) — `bot_data.db`, `bot.db`, `card_file_ids.db`, `edges.db`,
`moq.db`, `mzansi_bot.db`, `mzansiedge.db`, `narrative_cache.db`,
`odds.db` — are not in the symlink farm. Investigation needed
post-cutover whether anything writes to them; if so, add to farm.
Pre-flight read confirms `data/<same-name>.db` exists for the active
ones, so the top-level files are likely stale aliases.

## .venv strategy

`.venv` is symlinked from prod to dev tree (`bot-prod/.venv -> bot/.venv`)
to avoid duplicating ~700 MB per deploy. Trade-off: a `pip install`
mid-deploy in the dev tree would be visible to prod immediately. Operator
discipline: do not install during a deploy window. If a pip-level upgrade
is needed, run it outside business hours and recycle the bot afterwards.

EOF
fi

if [ "$MODE" != "--md" ]; then
    echo ''
    echo '=== END inventory ==='
    echo 'Re-run with --md to produce a markdown report.'
fi
