#!/usr/bin/env python3
# ruff: noqa
"""W91-P3 one-shot remediation — apply the verdict cap to existing cached
narratives whose Verdict body exceeds `_VERDICT_MAX_CHARS`.

Root cause (now fixed in `scripts/pregenerate_narratives.py`):
`cap_verdict_in_narrative()` was previously only invoked inside the
`gold/diamond` quality-gate branch. Silver and bronze narratives generated by
the W84 Sonnet polish path bypassed the cap and could land in
`narrative_cache` with 220–314-char verdicts, violating the 200-char hard cap
documented in `narrative_spec.py`.

This script:
  1. Scans `narrative_cache` for entries whose plain-text Verdict body
     exceeds `_VERDICT_MAX_CHARS` (200).
  2. Rewrites the Verdict body using `_cap_verdict` (clips + trailing period).
  3. Preserves the trailing `<b>SA Bookmaker Odds:</b>` block so users still
     see the quoted odds/bookmaker.
  4. Writes the updated narrative back with an ISO timestamp bump so the
     anti-stale cache gate re-serves it immediately.

Idempotent: running twice is a no-op.  Running after the next full
`pregenerate_narratives` sweep is also a no-op.
"""
from __future__ import annotations

import os
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

BOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BOT_DIR))

from narrative_spec import _VERDICT_MAX_CHARS, _cap_verdict  # noqa: E402

ODDS_DB = Path("/home/paulsportsza/scrapers/odds.db")
TROPHY = "\U0001f3c6"  # 🏆
SA_ODDS_MARKER = "<b>SA Bookmaker Odds:</b>"


def _cap_verdict_preserve_tail(html: str) -> tuple[str, bool]:
    """Cap the Verdict body without losing the SA Bookmaker Odds block.

    Returns (new_html, was_modified).
    """
    idx = html.find(TROPHY)
    if idx == -1:
        return html, False
    newline_pos = html.find("\n", idx)
    if newline_pos == -1:
        return html, False
    header_line = html[: newline_pos + 1]
    body_and_tail = html[newline_pos + 1 :]

    tail_idx = body_and_tail.find(SA_ODDS_MARKER)
    if tail_idx >= 0:
        body_segment = body_and_tail[:tail_idx]
        tail_segment = body_and_tail[tail_idx:]
    else:
        body_segment = body_and_tail
        tail_segment = ""

    body_plain = re.sub(r"<[^>]+>", "", body_segment).strip()
    if len(body_plain) <= _VERDICT_MAX_CHARS:
        return html, False

    capped = _cap_verdict(body_plain)
    # Keep a single blank line between verdict body and the bookmaker odds
    # block for consistent rendering (mirrors the live generator output).
    separator = "\n\n" if tail_segment else ""
    new_html = header_line + capped + separator + tail_segment
    return new_html, True


def main() -> int:
    if not ODDS_DB.exists():
        print(f"ERROR: odds.db not found at {ODDS_DB}", file=sys.stderr)
        return 2

    # Must open RW — the bot/pregen pipeline holds WAL so concurrent writes are
    # safe, but we still set busy_timeout to be kind to the live cron.
    conn = sqlite3.connect(str(ODDS_DB), timeout=30.0)
    conn.execute("PRAGMA busy_timeout=30000;")

    rows = conn.execute(
        "SELECT match_id, narrative_html, created_at FROM narrative_cache"
    ).fetchall()
    print(f"Scanning {len(rows)} cache rows…")

    fixed = 0
    skipped = 0
    untouched = 0
    now_iso = datetime.now(timezone.utc).isoformat()

    for match_id, html, created_at in rows:
        if not html:
            skipped += 1
            continue
        new_html, modified = _cap_verdict_preserve_tail(html)
        if not modified:
            untouched += 1
            continue
        # Bump created_at so the cache freshness gate re-serves this version.
        conn.execute(
            "UPDATE narrative_cache SET narrative_html = ?, created_at = ? WHERE match_id = ?",
            (new_html, now_iso, match_id),
        )
        fixed += 1
        print(f"  capped {match_id}")

    conn.commit()
    conn.close()

    print(f"\nDone — fixed {fixed}, untouched {untouched}, skipped {skipped}")
    return 0 if fixed >= 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
